version: '3'

services:
  mariadb:
    image: 'mariadb:10.6.4-focal'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp1
    volumes:
      - ./scripts:/scripts

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    restart: always


