- name: tp1
  hosts: victim
  become: yes

  roles:
  - docker

  tasks:
  - name: get docker-compose
    become: yes
    get_url:
      url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '+x'